[package]
name = "edgekv"
version = "0.1.0"
authors = ["mambisi <lilbizi96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.2.1"
anyhow = "1.0.39"